/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://464dm5gj35dxlc32xz26ntibsa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ignkd6gouvdvxpbshknzisomgy",
    "aws_cognito_identity_pool_id": "us-east-2:6d92184c-8c51-49cb-ac1a-4ae43daf5d6f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_QvslqWHy3",
    "aws_user_pools_web_client_id": "71qg3cnq44r4bb3jtq39odml5i",
    "oauth": {}
};


export default awsmobile;
